#!/bin/sh
python3 /Users/qmtruong92/Code/mp4/download.py

# Create functions to truncate & concatenate
filename=$(ls -t1 | head -n 1)
filename=${filename%.*} # truncate the file extension
filename=${filename}.mp3 # concatenate the .mp3 file extension

# Save the file into my music folder
if [ -f *.webm ]
    then
        ffmpeg -i *.webm -ab 128k /Users/qmtruong92/Music/"$filename"
        find . -name "*.webm" -type f -delete
elif [ -f *.mp4 ]
    then
        ffmpeg -i *.mp4 -ab 128k /Users/qmtruong92/Music/"$filename"
        find . -name "*.mp4" -type f -delete
fi

# Print the metadata of the MP3
python2 metadata.py
